# Generated by Django 4.0.6 on 2022-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_seats',
            field=models.IntegerField(),
        ),
    ]
