# Generated by Django 4.0.6 on 2022-07-25 21:35

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_booked_seats_alter_event_num_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=250, validators=[events.models.validate_event]),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=20),
        ),
    ]
