# Generated by Django 4.0.6 on 2022-07-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_booked_seats_alter_event_num_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
